### ISSUE TITLE
timeout connecting to server

### ISSUE THREAD

**Issue by tekkkon** [hjespers/teslams#113]
keep getting timeout errors with the example, anyone has the issue?

Error parsing response to oauth token request
{ Error: connect ETIMEDOUT xx.xx.xx.xx:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'xx.xx.xx.xx',
  port: 443 }

**Comment by tekkkon** [comment]
https://teslamotorsclub.com/tmc/threads/model-s-rest-api.13410/page-96

this may help answer the questions

**Comment by wga22** [comment]
You can set a proxy via the command line.

export http_proxy="http://184.175.106.139:80/"

good list of proxies are here:
https://www.us-proxy.org/

I am working on a js to pull these, and set it, because they seem to go down regularly.  Feel free to take:

https://github.com/wga22/nodejs/blob/master/vacuum/proxylist.js
