### ISSUE TITLE
blocked by the DoS protection systems

### ISSUE THREAD

**Issue by tekkkon** [hjespers/teslams#87]
hey, so excited to try out multiple commands within the example, turned out I seem to be blocked bu their Dos. any way to recover it ?

**Comment by hjespers** [comment]
Wait 24 hours and the block will clear. If you can't wait then change your IP address because the block is not on your account, it's on your IP.

I find that the block kicks in as soon as you get the API 4-5 times in a few seconds. That's why I put a 5 second delay in some of my example apps and I have a counter in streaming that pauses after 6 requests per minute.
